# Generated by Django 4.2.16 on 2026-01-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id,自增')),
                ('code', models.IntegerField(verbose_name='演员code，豆瓣获取')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(default='男', max_length=1, null=True, verbose_name='性别')),
                ('birth_time', models.CharField(max_length=15, null=True, verbose_name='出生年月')),
                ('birth_area', models.CharField(max_length=200, null=True, verbose_name='出生地')),
                ('posiiton', models.CharField(max_length=200, null=True, verbose_name='职业')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='豆瓣主页')),
                ('cover_url', models.CharField(max_length=200, null=True, verbose_name='封面链接')),
            ],
            options={
                'db_table': 'actor_info',
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id,自增')),
                ('code', models.IntegerField(verbose_name='导演code,豆瓣获取')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(default='男', max_length=1, null=True, verbose_name='性别')),
                ('birth_time', models.CharField(max_length=15, null=True, verbose_name='出生年月')),
                ('birth_area', models.CharField(max_length=200, null=True, verbose_name='出生地')),
                ('posiiton', models.CharField(max_length=200, null=True, verbose_name='职业')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='豆瓣主页')),
                ('cover_url', models.CharField(max_length=200, null=True, verbose_name='封面链接')),
            ],
            options={
                'db_table': 'director_info',
            },
        ),
        migrations.CreateModel(
            name='DoubanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id,自增')),
                ('code', models.IntegerField(null=True, verbose_name='豆瓣电影code')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('cover_url', models.CharField(max_length=300, null=True, verbose_name='封面链接')),
                ('regions', models.CharField(max_length=300, null=True, verbose_name='区域，多个区域用逗号隔开')),
                ('title', models.CharField(max_length=300, verbose_name='电影名')),
                ('url', models.CharField(max_length=300, null=True, verbose_name='电影链接')),
                ('release_date', models.CharField(max_length=10, null=True, verbose_name='上映时间')),
                ('actor_count', models.IntegerField(null=True, verbose_name='演员人数')),
                ('vote_count', models.IntegerField(null=True, verbose_name='投票人数')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='评分')),
                ('en_id', models.IntegerField(null=True, verbose_name='艺恩电影id')),
            ],
            options={
                'db_table': 'douban_movie_info',
            },
        ),
        migrations.CreateModel(
            name='EnModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id, 自增')),
                ('code', models.IntegerField(verbose_name='电影code，艺恩获取')),
                ('movie_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('avg_audience_count', models.IntegerField(verbose_name='场均人次')),
                ('release_time', models.CharField(max_length=10, verbose_name='上映时间')),
                ('avg_boxoffice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均票价')),
                ('boxoffice', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='累计票房')),
                ('rank', models.IntegerField(verbose_name='排名')),
            ],
            options={
                'db_table': 'en_movie_info',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id,自增')),
                ('code', models.IntegerField(verbose_name='类型code,豆瓣获取')),
                ('name', models.CharField(max_length=10, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'type_info',
            },
        ),
        migrations.CreateModel(
            name='MovieTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.doubanmodel')),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.typemodel')),
            ],
            options={
                'db_table': 'movie_type',
            },
        ),
        migrations.CreateModel(
            name='MovieDirectorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('director_id', models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.directormodel')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.doubanmodel')),
            ],
            options={
                'db_table': 'movie_director',
            },
        ),
        migrations.CreateModel(
            name='MovieActorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('actor_id', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.actormodel')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movieslib.doubanmodel')),
            ],
            options={
                'db_table': 'movie_actor',
            },
        ),
    ]
